name: GloomTweak
version: '1.0.1'
main: cn.gloomTweak.Main
api-version: '1.21'
folia-supported: true
commands:
  gloomtweak:
    description: Main command.
    aliases:
      - gt
    usage: /<command>

permissions:
  gloomtweak.reload:
    description: Allow the player to reload the plugin.
    default: op
  gloomtweak.help:
    description: Allow the player to get the help.
    default: true